# Configuraci贸n de la aplicaci贸n
spring:
  application:
    name: product-management-api

# Configuraci贸n de Springdoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    showExtensions: true
    showCommonExtensions: true
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    doc-expansion: none
    display-operation-id: false
  show-actuator: true
  packages-to-scan: com.example.project

# Configuraci贸n de logging
logging:
  level:
    com.example.project: DEBUG
    org.springframework.web: INFO
    org.springdoc: DEBUG

